import Darwin
import Foundation

/// Runs the system HTML importer in a disposable helper process. The app only
/// receives bounded RTF generated by that helper, so malformed HTML cannot block
/// the app's main actor or leave an importer running indefinitely.
actor HTMLPreviewRenderer: HTMLPreviewRendering {
    private enum CachedResult {
        case rendered(Data)
        case unavailable
    }

    private struct ActiveRequest {
        let id: UUID
        let key: String
        let task: Task<Data?, Never>
    }

    private let executableURL: URL?
    private let timeout: Duration
    private let maximumPhysicalFootprintBytes: UInt64
    private var activeRequest: ActiveRequest?
    private var latestGeneration: UInt64 = 0
    private var cache: [String: CachedResult] = [:]
    private var cacheOrder: [String] = []

    init(
        executableURL: URL? = HTMLPreviewRenderer.defaultExecutableURL(),
        timeout: Duration = .seconds(1),
        maximumPhysicalFootprintBytes: UInt64 = HTMLPreviewLimits.maximumPhysicalFootprintBytes
    ) {
        self.executableURL = executableURL
        self.timeout = timeout
        self.maximumPhysicalFootprintBytes = maximumPhysicalFootprintBytes
    }

    func render(html: Data) async -> Data? {
        guard !html.isEmpty, html.count <= HTMLPreviewLimits.maximumInputBytes else { return nil }
        let key = HashUtil.sha256HTMLOnly(html)
        if let activeRequest, activeRequest.key == key {
            return await activeRequest.task.value
        }

        latestGeneration &+= 1
        let generation = latestGeneration
        let previousRequest = activeRequest
        previousRequest?.task.cancel()
        if let previousRequest {
            _ = await previousRequest.task.value
        }
        if activeRequest?.id == previousRequest?.id {
            activeRequest = nil
        }
        guard generation == latestGeneration, !Task.isCancelled else { return nil }
        if let cached = cache[key] {
            return switch cached {
            case .rendered(let data): data
            case .unavailable: nil
            }
        }
        guard let executableURL else { return nil }

        let requestID = UUID()
        let timeout = timeout
        let maximumPhysicalFootprintBytes = maximumPhysicalFootprintBytes
        let task = Task.detached(priority: .utility) {
            Self.runHelper(
                executableURL: executableURL,
                html: html,
                timeout: timeout,
                maximumPhysicalFootprintBytes: maximumPhysicalFootprintBytes
            )
        }
        activeRequest = ActiveRequest(id: requestID, key: key, task: task)
        let result = await task.value
        if activeRequest?.id == requestID {
            activeRequest = nil
        }
        guard generation == latestGeneration, !task.isCancelled else { return nil }
        store(result.map(CachedResult.rendered) ?? .unavailable, for: key)
        return result
    }

    nonisolated static func defaultExecutableURL(
        bundle: Bundle = .main,
        fileManager: FileManager = .default
    ) -> URL? {
        var candidates: [URL] = []
        if let executableURL = bundle.executableURL {
            candidates.append(
                executableURL.deletingLastPathComponent()
                    .deletingLastPathComponent()
                    .appendingPathComponent("Helpers/ClipboardHTMLRenderer")
            )
            candidates.append(
                executableURL.deletingLastPathComponent()
                    .appendingPathComponent("ClipboardHTMLRenderer")
            )
        }
        return candidates.first { fileManager.isExecutableFile(atPath: $0.path) }
    }

    private func store(_ result: CachedResult, for key: String) {
        cache[key] = result
        cacheOrder.removeAll { $0 == key }
        cacheOrder.append(key)
        while cacheOrder.count > 20 {
            cache.removeValue(forKey: cacheOrder.removeFirst())
        }
    }

    nonisolated private static func runHelper(
        executableURL: URL,
        html: Data,
        timeout: Duration,
        maximumPhysicalFootprintBytes: UInt64
    ) -> Data? {
        guard !currentTaskIsCancelled() else { return nil }
        let fileManager = FileManager.default
        let directory = fileManager.temporaryDirectory
            .appendingPathComponent("ClipboardHTMLPreview-\(UUID().uuidString)", isDirectory: true)
        let inputURL = directory.appendingPathComponent("input.html")
        let outputURL = directory.appendingPathComponent("output.rtf")
        do {
            guard !currentTaskIsCancelled() else { return nil }
            try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
            try fileManager.setAttributes(
                [.posixPermissions: NSNumber(value: Int16(0o700))],
                ofItemAtPath: directory.path
            )
            defer { try? fileManager.removeItem(at: directory) }
            guard !currentTaskIsCancelled() else { return nil }
            try html.write(to: inputURL, options: .atomic)
            guard !currentTaskIsCancelled() else { return nil }

            let process = Process()
            process.executableURL = executableURL
            process.arguments = [inputURL.path, outputURL.path]
            process.standardOutput = FileHandle.nullDevice
            process.standardError = FileHandle.nullDevice
            let completion = DispatchSemaphore(value: 0)
            process.terminationHandler = { _ in completion.signal() }
            guard !currentTaskIsCancelled() else { return nil }
            try process.run()

            let deadline = ContinuousClock.now + timeout
            while completion.wait(timeout: .now() + .milliseconds(20)) == .timedOut {
                if currentTaskIsCancelled()
                    || physicalFootprint(of: process.processIdentifier)
                        .map({ $0 > maximumPhysicalFootprintBytes }) ?? true
                    || ContinuousClock.now >= deadline {
                    stop(process, completion: completion)
                    return nil
                }
            }
            guard process.terminationStatus == 0,
                  let attributes = try? fileManager.attributesOfItem(atPath: outputURL.path),
                  let size = attributes[.size] as? NSNumber,
                  size.intValue > 0,
                  size.intValue <= HTMLPreviewLimits.maximumOutputBytes else { return nil }
            return try Data(contentsOf: outputURL, options: .mappedIfSafe)
        } catch {
            return nil
        }
    }

    nonisolated private static func currentTaskIsCancelled() -> Bool {
        withUnsafeCurrentTask { $0?.isCancelled ?? false }
    }

    nonisolated private static func physicalFootprint(of processID: pid_t) -> UInt64? {
        var info = rusage_info_v0()
        let result = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(to: rusage_info_t?.self, capacity: 1) {
                proc_pid_rusage(processID, RUSAGE_INFO_V0, $0)
            }
        }
        return result == 0 ? info.ri_phys_footprint : nil
    }

    nonisolated private static func stop(
        _ process: Process,
        completion: DispatchSemaphore
    ) {
        guard process.isRunning else { return }
        process.terminate()
        if completion.wait(timeout: .now() + .milliseconds(100)) == .timedOut,
           process.isRunning {
            kill(process.processIdentifier, SIGKILL)
            _ = completion.wait(timeout: .now() + .milliseconds(100))
        }
    }
}
